spring.application.name=secure_document_vault

spring.datasource.url=jdbc:postgresql://localhost/secure_doc_vault_db

spring.datasource.username=postgres
spring.datasource.password=secdocvault123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
